//FILE GENERATED BY CHATGPT
using UnityEditor;
using UnityEngine;

public class BuildScript
{
    public static void BuildGame()
    {
        // Define the build path
        string buildPath = "exec";

        // Detect the platform
        BuildTarget targetPlatform;
        string fileExtension;

        if (Application.platform == RuntimePlatform.WindowsEditor)
        {
            targetPlatform = BuildTarget.StandaloneWindows64;
            fileExtension = ".exe";
        }
        else if (Application.platform == RuntimePlatform.OSXEditor)
        {
            targetPlatform = BuildTarget.StandaloneOSX;
            fileExtension = "";
        }
        else if (Application.platform == RuntimePlatform.LinuxEditor)
        {
            targetPlatform = BuildTarget.StandaloneLinux64;
            fileExtension = "";
        }
        else
        {
            Debug.LogError("Unsupported platform!");
            return;
        }

        // Ensure the build path exists
        System.IO.Directory.CreateDirectory(buildPath);

        // Define the full build file path
        string buildFilePath = $"{buildPath}/UnityEnvironment{fileExtension}";

        // Build options
        BuildPlayerOptions buildPlayerOptions = new BuildPlayerOptions
        {
            scenes = new[] { "Assets/Content/Scenes/FPS_Training.unity" }, // Adjust to your main scene path
            locationPathName = buildFilePath,
            target = targetPlatform,
            options = BuildOptions.None
        };

        // Perform the build
        BuildPipeline.BuildPlayer(buildPlayerOptions);

        Debug.Log($"Build completed for {targetPlatform} at {buildFilePath}");
    }
}
